"""Modify route table float to int

Revision ID: 468f0308ce5d
Revises: dd533b980f28
Create Date: 2024-10-25 14:34:40.463895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '468f0308ce5d'
down_revision: Union[str, None] = 'dd533b980f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('route', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route', 'longitude',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('route', 'latitude',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
