# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby "2.7.8"

# gem "rails"
gem "google-protobuf", "3.25.5"
gem "grpc", "1.65.2"
gem "grpc-tools"
gem "multi_json"
gem "dotenv"