# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_sample.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'auth_sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61uth_sample.proto\x12\x0cgrpc.testing\"X\n\x07Request\x12#\n\rfill_username\x18\x04 \x01(\x08R\x0c\x66illUsername\x12(\n\x10\x66ill_oauth_scope\x18\x05 \x01(\x08R\x0e\x66illOauthScope\"G\n\x08Response\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\x12\x1f\n\x0boauth_scope\x18\x03 \x01(\tR\noauthScope2I\n\x0bTestService\x12:\n\tUnaryCall\x12\x15.grpc.testing.Request\x1a\x16.grpc.testing.ResponseBt\n\x10\x63om.grpc.testingB\x0f\x41uthSampleProtoP\x01\xa2\x02\x03GTX\xaa\x02\x0cGrpc.Testing\xca\x02\x0cGrpc\\Testing\xe2\x02\x18Grpc\\Testing\\GPBMetadata\xea\x02\rGrpc::Testingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.grpc.testingB\017AuthSampleProtoP\001\242\002\003GTX\252\002\014Grpc.Testing\312\002\014Grpc\\Testing\342\002\030Grpc\\Testing\\GPBMetadata\352\002\rGrpc::Testing'
  _globals['_REQUEST']._serialized_start=35
  _globals['_REQUEST']._serialized_end=123
  _globals['_RESPONSE']._serialized_start=125
  _globals['_RESPONSE']._serialized_end=196
  _globals['_TESTSERVICE']._serialized_start=198
  _globals['_TESTSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
