# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_uploader_pb2 as file__uploader__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


class FileUploaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFile = channel.unary_unary(
                '/mypackage.FileUploader/SendFile',
                request_serializer=file__uploader__pb2.FileData.SerializeToString,
                response_deserializer=google_dot_rpc_dot_status__pb2.Status.FromString,
                _registered_method=True)


class FileUploaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileUploaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=file__uploader__pb2.FileData.FromString,
                    response_serializer=google_dot_rpc_dot_status__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.FileUploader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mypackage.FileUploader', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileUploader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.FileUploader/SendFile',
            file__uploader__pb2.FileData.SerializeToString,
            google_dot_rpc_dot_status__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
